### PR TITLE
chore: update to Silero VAD V5 Model and ORT 2.0.0-rc.10

### LINKED ISSUE #38: Does not build on Rust 1.80.1
How to reproduce:
```
$ cargo new vad_test
$ cd vad_test/
$ cargo add voice_activity_detector

    Updating crates.io index
      Adding voice_activity_detector v0.1.0 to dependencies
             Features:
             - async
             - load-dynamic
    Updating crates.io index
     Locking 107 packages to latest compatible versions
      Adding generic-array v0.14.7 (latest: v1.1.0)
      Adding idna v0.5.0 (latest: v1.0.2)
      Adding linux-raw-sys v0.4.14 (latest: v0.6.5)
      Adding ndarray v0.15.6 (latest: v0.16.1)
      Adding typed-builder v0.18.2 (latest: v0.20.0)
      Adding typed-builder-macro v0.18.2 (latest: v0.20.0)
      Adding wasi v0.11.0+wasi-snapshot-preview1 (latest: v0.13.2+wasi-0.2.1)
      Adding windows-sys v0.52.0 (latest: v0.59.0)
$ cargo check
[...]
    Checking voice_activity_detector v0.1.0
error[E0277]: the trait bound `Value: From<ArrayBase<ViewRepr<&f32>, Dim<[usize; 2]>>>` is not satisfied
  --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/voice_activity_detector-0.1.0/src/vad.rs:51:22
   |
51 |           let inputs = ort::inputs![
   |  ______________________^
52 | |             "input" => input.view(),
53 | |             "sr" => sample_rate.view(),
54 | |             "h" => self.h.view(),
55 | |             "c" => self.c.view(),
56 | |         ]
   | |_________^ the trait `From<ArrayBase<ViewRepr<&f32>, Dim<[usize; 2]>>>` is not implemented for `Value`, which is required by `Value: TryFrom<ArrayBase<ViewRepr<&f32>, Dim<[usize; 2]>>>`
   |
   = help: the following other types implement trait `From<T>`:
             <Value as From<Value<DynTensorValueType>>>
             <Value as From<Value<TensorValueType<T>>>>
   = note: required for `ArrayBase<ViewRepr<&f32>, Dim<[usize; 2]>>` to implement `Into<Value>`
   = note: required for `Value` to implement `TryFrom<ArrayBase<ViewRepr<&f32>, Dim<[usize; 2]>>>`
   = note: this error originates in the macro `ort::inputs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Value: From<ArrayBase<ViewRepr<&i64>, Dim<[usize; 1]>>>` is not satisfied
  --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/voice_activity_detector-0.1.0/src/vad.rs:51:22
   |
51 |           let inputs = ort::inputs![
   |  ______________________^
52 | |             "input" => input.view(),
53 | |             "sr" => sample_rate.view(),
54 | |             "h" => self.h.view(),
55 | |             "c" => self.c.view(),
56 | |         ]
   | |_________^ the trait `From<ArrayBase<ViewRepr<&i64>, Dim<[usize; 1]>>>` is not implemented for `Value`, which is required by `Value: TryFrom<ArrayBase<ViewRepr<&i64>, Dim<[usize; 1]>>>`
   |
   = help: the following other types implement trait `From<T>`:
             <Value as From<Value<DynTensorValueType>>>
             <Value as From<Value<TensorValueType<T>>>>
   = note: required for `ArrayBase<ViewRepr<&i64>, Dim<[usize; 1]>>` to implement `Into<Value>`
   = note: required for `Value` to implement `TryFrom<ArrayBase<ViewRepr<&i64>, Dim<[usize; 1]>>>`
   = note: this error originates in the macro `ort::inputs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Value: From<ArrayBase<ViewRepr<&f32>, Dim<[usize; 3]>>>` is not satisfied
  --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/voice_activity_detector-0.1.0/src/vad.rs:51:22
   |
51 |           let inputs = ort::inputs![
   |  ______________________^
52 | |             "input" => input.view(),
53 | |             "sr" => sample_rate.view(),
54 | |             "h" => self.h.view(),
55 | |             "c" => self.c.view(),
56 | |         ]
   | |_________^ the trait `From<ArrayBase<ViewRepr<&f32>, Dim<[usize; 3]>>>` is not implemented for `Value`, which is required by `Value: TryFrom<ArrayBase<ViewRepr<&f32>, Dim<[usize; 3]>>>`
   |
   = help: the following other types implement trait `From<T>`:
             <Value as From<Value<DynTensorValueType>>>
             <Value as From<Value<TensorValueType<T>>>>
   = note: required for `ArrayBase<ViewRepr<&f32>, Dim<[usize; 3]>>` to implement `Into<Value>`
   = note: required for `Value` to implement `TryFrom<ArrayBase<ViewRepr<&f32>, Dim<[usize; 3]>>>`
   = note: this error originates in the macro `ort::inputs` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
    --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/voice_activity_detector-0.1.0/src/vad.rs:73:23
     |
73   |         self.h.assign(&hn.view());
     |                ------ ^^^^^^^^^^ expected `&ArrayBase<_, _>`, found `&ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>`
     |                |
     |                arguments to this method are incorrect
     |
     = note: `ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>` and `ArrayBase<_, _>` have similar names, but are actually distinct types
note: `ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>` is defined in crate `ndarray`
    --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.16.1/src/lib.rs:1280:1
     |
1280 | pub struct ArrayBase<S, D>
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `ArrayBase<_, _>` is defined in crate `ndarray`
    --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/lib.rs:1268:1
     |
1268 | pub struct ArrayBase<S, D>
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: perhaps two different versions of crate `ndarray` are being used?
note: method defined here
    --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_methods.rs:2349:12
     |
2349 |     pub fn assign<E: Dimension, S2>(&mut self, rhs: &ArrayBase<S2, E>)
     |            ^^^^^^

error[E0308]: mismatched types
    --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/voice_activity_detector-0.1.0/src/vad.rs:74:23
     |
74   |         self.c.assign(&cn.view());
     |                ------ ^^^^^^^^^^ expected `&ArrayBase<_, _>`, found `&ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>`
     |                |
     |                arguments to this method are incorrect
     |
     = note: `ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>` and `ArrayBase<_, _>` have similar names, but are actually distinct types
note: `ArrayBase<ViewRepr<&f32>, Dim<IxDynImpl>>` is defined in crate `ndarray`
    --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.16.1/src/lib.rs:1280:1
     |
1280 | pub struct ArrayBase<S, D>
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `ArrayBase<_, _>` is defined in crate `ndarray`
    --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/lib.rs:1268:1
     |
1268 | pub struct ArrayBase<S, D>
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: perhaps two different versions of crate `ndarray` are being used?
note: method defined here
    --> /home/eugenio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_methods.rs:2349:12
     |
2349 |     pub fn assign<E: Dimension, S2>(&mut self, rhs: &ArrayBase<S2, E>)
     |            ^^^^^^

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `voice_activity_detector` (lib) due to 5 previous errors
```

### LINKED ISSUE #48: Update the model file
Hello, the Silero model changed some time ago, here is the commit for the rust example:
https://github.com/snakers4/silero-vad/commit/a7bd2dd38f9f365ce9846776989d5c90a1a3fc89
Like you can see the input and output is now different

### PR DESCRIPTION
**Pull request by jim60105**
- Upgraded to the Silero VAD V5 model, supporting only 8kHz/256 and 16kHz/512 sample rate and chunk size combinations.
- Updated `vad.rs` to match the new model interface and state handling.
- Improved error messages for unsupported configurations.
- Locked `ort` and `ort-sys` dependencies to `=2.0.0-rc.10` for build stability.
- Updated documentation to reflect new model requirements.

## **Breaking changes:**

- The crate now uses the Silero VAD V5 model, which only supports fixed window sizes:
  - For 8 kHz sample rate, only a 256-sample chunk is allowed.
  - For 16 kHz sample rate, only a 512-sample chunk is allowed.
- Any other sample rate or chunk size combination is no longer supported and will result in an error.
- [Here is the source of the model limitations.](https://github.com/snakers4/silero-vad/releases/tag/v5.0)

These changes break compatibility with previous versions. User has to update their code to match the new model requirements.

> I am new in Rust. Please feel free to adjust the code if it does not follow professional conventions.

Fixes #38, Fixes #48
This also covers PR #49

### CODE REVIEW

**Comment by DAIMENGEN** [comment]
I'm wondering if it might be a bit early to upgrade to 2.0.0-rc.10, since it's still a pre-release. Both ort and ort-sys are currently in the 2.0.0-rc.xx phase, so it's likely that more RC versions (like rc.11, rc.12, etc.) will follow — possibly with breaking changes. That could introduce some churn and extra maintenance work.

Would it maybe make sense to hold off on the upgrade until the stable 2.0.0 is out — unless there's a strong reason to move to the RC now?

**Comment by jim60105** [comment]
v1.16.3 (non RC) 2023/11/13  
v2.0.0-rc.9 2024/11/22  
v2.0.0-rc.10 2025/06/05

According to the git logs, this project originally use version 2.0.0-alpha.4 (2023/12/28).
Given this history, it seems unlikely that a stable v1 version can be reverted to.
Regarding the comparison between v2.0.0-rc.9 and v2.0.0-rc.10, I believe there isn’t a significant difference from a project management standpoint, simply opt for the newer version.

The breaking change in this PR is due to upgrading Silero VAD to version 5; the specific version of ORT used should not significantly affect users?

**Comment by jim60105** [comment]
I initially picked up your commit =2.0.0-rc.9 (we actually needed it), and only upgraded to 2.0.0-rc.10 at the last minute.
Reverting the last commit will bring us back to rc.9.
image

**Comment by DAIMENGEN** [comment]
Thanks, that helps clarify things — I see it more clearly now.

**Review by nkeenan38 — APPROVED** [review]

**Comment by nkeenan38** [comment]
@jim60105 Thank you for the contribution. I wanted to apologize for the delay. My personal life has been busy and I've neglected this project as a result. Sorry for any inconvenience and thanks again for the help!
